### ISSUE TITLE
Unable To Open Lab Templates

### ISSUE THREAD

**Issue by nelsonconnor6** [Watts-College/crj-507-spring-2024#11]
Professor Young, 

For some reason I am having issues opening the Lab templates. I can't open them in RStudio or even in any other application. I'm not very knowledgeable around computers and the way files work so if I'm missing something obvious, forgive me. Could you point me in the right direction to troubleshoot this issue? 

Thank you, 

Connor

**Comment by jacobtnyoung** [comment]
Hi @nelsonconnor6 ! When you say the templates will not open, can you give more details? Here are some instructions that should help:

1. Click on the link for the template (this will download the file to your Downloads folder)
2. The file that is downloaded is a .zip file. Open it and it will decompress, creating a .Rmd file. This is the template.
3. Open the .Rmd file.

At this point, if there is an error or something occurring at step 3, then send a screen shot (or several) of what is going on.

If we can fix it here, book a time during office hours and we can work through it together.

**Comment by jacobtnyoung** [comment]
Hi @nelsonconnor6! Just wanted to check in and see whether you were able to resolve this issue. 🤞🏼

**Comment by nelsonconnor6** [comment]
Professor Young, It looks like your help worked! Thanks so much! All the best, Connor Nelson Sent from my iPhoneOn Jan 29, 2024, at 13:20, jacobtnyoung ***@***.***> wrote:﻿
Hi @nelsonconnor6! Just wanted to check in and see whether you were able to resolve this issue. 🤞🏼
