### ISSUE TITLE
Opening online article & matrix 

### ISSUE THREAD

**Issue by jjgillis0** [Watts-College/crj-507-spring-2024#13]
Hello Professor Young~ 
First, I'm trying to open the Grund/Densley article, but ASU does not appear on the list.

Also, I'm trying to figure out the matrix for the London Gangs. In lab 2 it was easy from our own network, but after the gplot and getting this below, I'm very confused. 

Any input is appreciated. Thank you. 
Jenny Gillis

![Screenshot 2024-01-29 135122](https://github.com/Watts-College/crj-507-spring-2024/assets/156146889/2baaffcd-ed4c-43ec-b7a1-314ee33be07d)

**Comment by jjgillis0** [comment]
I figured it out :)

**Comment by jacobtnyoung** [comment]
Great! @jjgillis0

**Comment by jjgillis0** [comment]
My newest issue is my plot looks like this and here is my code:
library( sna, quietly=TRUE ) 
set.seed( 605 )
coords <- gplot( u.mat )
gplot( 
  u.mat, 
  gmode="graph", 
  arrowhead.cex=0.5, 
  edge.col="grey40", 
  label=rownames( u.mat ),
  label.col="blue",
  label.cex=1.2,
  coord = coords
  )
colSums( u.mat )
rowSums( u.mat )
deg.u.mat <- colSums( u.mat )
gplot(
  u.mat,
  gmode="graph", 
  arrowhead.cex=1.5, 
  edge.col="grey40", 
  label=rownames( u.mat ),
  label.col="blue",
  label.cex=0.5,
  vertex.cex = deg.u.mat,
  coord = coords
  )
![image](https://github.com/Watts-College/crj-507-spring-2024/assets/156146889/39dbee50-863f-4a1f-9402-a3510eb8f777)

**Comment by jacobtnyoung** [comment]
Hi @jjgillis0 without the code for the `u.mat` object, I can't reproduce what you have. But, I will use the code from a template:

```r


u.mat <- read.csv( 
  "https://github.com/jacobtnyoung/sna-textbook/raw/main/data/data-undirected-example.csv",
  as.is = TRUE,
  header = TRUE,
  row.names = 1 
)

library( sna, quietly=TRUE )

set.seed( 605 )

coords <- gplot( u.mat )

gplot(
  u.mat,
  gmode="graph",
  arrowhead.cex=0.5,
  edge.col="grey40",
  label=rownames( u.mat ),
  label.col="blue",
  label.cex=1.2,
  coord = coords
)

colSums( u.mat )

rowSums( u.mat )

deg.u.mat <- colSums( u.mat )

gplot(
  u.mat,
  gmode="graph",
  arrowhead.cex=1.5,
  edge.col="grey40",
  label=rownames( u.mat ),
  label.col="blue",
  label.cex=0.5,
  vertex.cex = deg.u.mat,
  coord = coords
)

```

This works for me. Probably what you are running into is that the degrees are too large for the plot to render.  For example, run this code:

```r

# load the libraries we need
library( sna )
library( network )

# define the path location for the file
loc <- "https://github.com/jacobtnyoung/sna-textbook/raw/main/data/data-london-gang-net.rds"
LondonGangNet <- readRDS( url(loc ) )

# look at the network
LondonGangNet

u.mat <- as.matrix(LondonGangNet)

library( sna, quietly=TRUE )

set.seed( 605 )

coords <- gplot( u.mat )

gplot(
  u.mat,
  gmode="graph",
  arrowhead.cex=0.5,
  edge.col="grey40",
  label=rownames( u.mat ),
  label.col="blue",
  label.cex=1.2,
  coord = coords
)

colSums( u.mat )

rowSums( u.mat )

deg.u.mat <- colSums( u.mat )

gplot(
  u.mat,
  gmode="graph",
  arrowhead.cex=1.5,
  edge.col="grey40",
  label=rownames( u.mat ),
  label.col="blue",
  label.cex=0.5,
  vertex.cex = deg.u.mat,
  coord = coords
)


```

Look at the largest value of the `deg.u.mat` object using `max( deg.u.mat )` . You will see that it is fairly large. You just need to rescale the value:

```r

deg.u.mat <- deg.u.mat / max(deg.u.mat)

```

Try that.

**Comment by jjgillis0** [comment]
Got it! That worked! Thank you.

**Comment by jacobtnyoung** [comment]
Great @jjgillis0 !
