### ISSUE TITLE
graph centralization for degree.

### ISSUE THREAD

**Issue by CGUEVARR** [Watts-College/crj-507-spring-2024#18]
Receiving an error for Part1 #5 with the following code 
# Your code here

dim( as.matrix( LondonGangNet ) )[1]

(sum(((max( deg.as.matrix(LondonGangNet)- deg.as.matrix(LondonGangNet)))))/( g-1)*( g-2))

group.deg.as.matrix(LondonGangNet)

This is the error:
Error in `deg.as.matrix()`:
! could not find function "deg.as.matrix"

**Comment by CGUEVARR** [comment]
I also tried this using the separate pieces code with no luck

**Comment by jacobtnyoung** [comment]
Hi @CGUEVARR . Looks like you solved this on your own?

**Comment by CGUEVARR** [comment]
@jacobtnyoung Yes, thank you!
