### ISSUE TITLE
Lab #4: Calculating Mean Degree, Mean Closeness Centrality, Mean Betweenness Centrality

### ISSUE THREAD

**Issue by jesscowart** [Watts-College/crj-507-spring-2024#20]
When we calculate the mean degree, mean closeness centrality, and mean betweenness centrality, are we using the raw or standardized scores?

Also, are we calculating the mean degree:
```{r}
mean.deg <- sum( deg.u.mat ) / dim( u.mat )[1] 
```
Or are we calculating the mean of the degree centrality scores:
```{r}
mean.deg <- mean( deg.LGN )
```

**Comment by jacobtnyoung** [comment]
Hi @jesscowart ! The raw score is fine. But feel free to report the standardized mean as well if you want.

**Comment by jesscowart** [comment]
Awesome, thanks! Sorry, to follow up...

Are we calculating the mean degree:
```{r}
mean.deg <- sum( deg.u.mat ) / dim( u.mat )[1] 
```
Or are we calculating the mean of the degree centrality scores:
```{r}
mean.deg <- mean( deg.LGN )
```

**Comment by jacobtnyoung** [comment]
Hi @jesscowart good question! It is the mean degree.

**Comment by jesscowart** [comment]
Thank you!
