### ISSUE TITLE
Lab #5 Vertex Attributes

### ISSUE THREAD

**Issue by jesscowart** [Watts-College/crj-507-spring-2024#21]
Hello!
For numbers 9 and 10 when we are trying to find who is most central in the network or which location is most central in the network, are we using the summary() function or is there another way to find this?
Thanks!

**Comment by jacobtnyoung** [comment]
Hi @jesscowart . You can either look through the degree distribution and report which one is largest, or you can use the `max()` function to return the largest number of a vector. Make sense?

**Comment by jesscowart** [comment]
Great, thank you!
