### ISSUE TITLE
Lab 4 Part 1 Question 5

### ISSUE THREAD

**Issue by n-galanos** [Watts-College/crj-507-spring-2024#22]
I am having an issue with "Calculate the graph centralization for degree, closeness, and betweenness centrality."

To calculate graph centralization I used the following code which worked;

cent.u <- centralization( LondonGangNet, degree, mode="graph" )

But when I try to code it for closeness and betweenness, I receive the following error;

>centralization(closeness(LondonGangNet))
**Error in as.edgelist.sna(dat) : 
  as.edgelist.sna input must be an adjacency matrix/array, edgelist matrix, network, or sparse matrix, or list thereof.**

I also tried the following code and received same error;

>closeness(cent.u)
**Error in as.edgelist.sna(dat) : 
  as.edgelist.sna input must be an adjacency matrix/array, edgelist matrix, network, or sparse matrix, or list thereof.**

Same issue when trying to code for betweenness

**Comment by n-galanos** [comment]
I might have figured it out... would it be;

> centralization( LondonGangNet, closeness, mode="graph" )

> centralization( LondonGangNet, betweenness, mode="graph" )

**Comment by CGUEVARR** [comment]
@n-galanos that's the code I used as well. Following to confirm this is correct.

**Comment by jacobtnyoung** [comment]
Hi @n-galanos ! Yes, that is correct! Nice job figuring it out. Thanks @CGUEVARR for chiming in!
