### ISSUE TITLE
Lab #5 Part 1 Question 2

### ISSUE THREAD

**Issue by n-galanos** [Watts-College/crj-507-spring-2024#25]
Hello, I am running into an error when working on calculating the density of the network (Part 1 question 2). 

>L <- sum( PaulRevereNet )
> 
> N <- dim( PaulRevereNet )[1]
> 
> M <- dim( PaulRevereNet )[2]
> 
> density.PaulRevereNet <- L / ( N * M )
Error in L/(N * M) : non-numeric argument to binary operator

**Comment by CGUEVARR** [comment]
Nicole- did you create a matrix from the network yet? That might be your issue. Try adding the following code to your set up....

dim( as.matrix( PaulRevereNet ) )[1]

**Comment by n-galanos** [comment]
that worked, thank you!

**Comment by jacobtnyoung** [comment]
Thanks @CGUEVARR for the assist! Glad you figured it out @n-galanos !
