### ISSUE TITLE
Unable to properly download Rmd file

### ISSUE THREAD

**Issue by AnthonyFicco** [Watts-College/crj-507-spring-2024#9]
So, I am able to perform the code in the console, but unable to transition it into the r markdown section. I have attached my first plot to show that I can complete every step, but I am not sure if my mistake is in my knitting or in my use of r markdown, or both. 

[Rplot Network 1.pdf](https://github.com/Watts-College/crj-507-spring-2024/files/14032026/Rplot.Network.1.pdf)

**Comment by jacobtnyoung** [comment]
Hi @AnthonyFicco! The plot is fine. Nice job. Go ahead and set eval=FALSE in your code chunk for that section and upload your .RMD file per the assignment. I can take a look through it and help diagnose the issue.

**Comment by jacobtnyoung** [comment]
Hi @AnthonyFicco . Take a look at the comments for your lab 2 assignment on Canvas.

**Comment by jacobtnyoung** [comment]
Hi @AnthonyFicco . Wanted to see whether you got this to work on your end.
